server:
  port: ${PORT:0}
spring:
  application:
    name: fexControl
  datasource:
    url: ${DATA_BASE_URL:jdbc:postgresql://localhost:5432/flexControl}
    username: ${POSTGRES_USER:root}
    password: ${POSTGRES_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
  jpa:
    database: postgresql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
